// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4LLNU26h740zgDYHv-VzlgUc8BWyIFGw',
    appId: '1:379228344132:web:1c57c56bf60dce07181111',
    messagingSenderId: '379228344132',
    projectId: 'explorefirebaseep',
    authDomain: 'explorefirebaseep.firebaseapp.com',
    storageBucket: 'explorefirebaseep.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk3j-X1vGnmKaEs_w3085nGAYGaTo9rDw',
    appId: '1:379228344132:android:1ad199fd5748aa5d181111',
    messagingSenderId: '379228344132',
    projectId: 'explorefirebaseep',
    storageBucket: 'explorefirebaseep.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmm_qlLrxFrcFCjnwfiVvH6HxfVj2QvTg',
    appId: '1:379228344132:ios:90fe4d58b186fe56181111',
    messagingSenderId: '379228344132',
    projectId: 'explorefirebaseep',
    storageBucket: 'explorefirebaseep.appspot.com',
    iosBundleId: 'com.example.firebaseAuthExplore',
  );
}
